# docker-compose.yml
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  facturacion-ocd:
    build: .
    volumes:
      - .:/facturacion-ocd
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      SECRET_KEY_BASE: "eaf94012067095b74138f8e1e08ca612a63ceedb81b6aae94e0944ec69d0280d60278101bf2bf7db4eeba3ad310cc1a7f6cff1061dc382af9ba3d9fb11d7d533"
      RAILS_ENV: "development"

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  db_data:
